language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'


mysql:
  database: travis_ci_drupal_module_example_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql


script: drush test-run 'Travis-CI Drupal Module Example' --uri=http://127.0.0.1:8080
